@isTest
public class IContractBaseComponentCtrlTest {
/*
    @testSetup static void createData(){
	     User auser = Utility_Test.createUser('testdummy@zycustest.com');
         insert auser;
     }
    
    
     @isTest static void testmethod1(){
         User userObj 				= [Select Id from User where UserName = 'testdummy@zycustest.com'];
         Test.startTest();
         System.runAs(userObj){
         	//IContractBaseComponentCtrl.getUIThemeDescription();    
         }
         Test.stopTest();
     }
     */
}